const schemas = {
    users:{
        userId:{
            type:String,
            required:true,
            unique:true
        },
        phone:{
            type:Number,
            required:true,
            unique:true
        },
        password:{
            type:String,
            required:true
        },
        nickName:{
            type:String,
            default:"新用户"
        },
        avatarUrl:{
            type:String,
            default:"/static/images/default.jpg"
        },
        age:{
            type:String||Number,
            default:"未知"
        },
        gender:{
            type:String,
            default:"未知"
        },
        birthday:{
            type:String,
            default:"1970-01-01"
        },
        provide:{
            type:String,
            default:"广东"
        },
        city:{
            type:String,
            default:"深圳"
        },
        token:{
            type:String
        },
        tokenCreate:{
            type:Number,
            default:Date.now
        },
        salt:{
            type:String
        }
    },
    chats:{
        chatToken:{
            type:String,
            unique:true,
            required:true
        },
        chatUsers:{
            type:[String],
            required:true
        },
        chatName:{
            type:String,
            required:true
        },
        chatType:{
            type:String,
            required:true
        },
        groupFace:{
            type:String,
        },
        userFace:{
            type:String,
        },
        lastModify:{
            type:Number
        },
        lastText:{
            type:String
        },
        lastUserId:{
            type:Number
        }
    },
    ucmaps:{
        userId:{
            type:Number,
            required:true
        },
        chatToken:{
            type:String,
            required:true
        }
    },
    friends:{
        userId:{
            type:String,
            required:true,
            unique:true
        },
        friends:{
            type:[String],
            required:true
        }
    }
}

module.exports=schemas;